### TO-MODIFY: Location of directories
reads_dir: "/scratch/boutroux/VMR_reads"
assembly_dir: "/scratch/boutroux/VMR_assemblies"
results_dir: "/scratch/boutroux/VMR_results"

### TO-MODIFY: Threads
pyrodigal:
  threads: 20
hmmsearch:
  threads: 8
seqkit:
  threads: 4
minimap2:
  threads: 8
coverm:
  threads: 4
